# Numpy 1일차 

In [2]:
#라이브러리가 설치 잘 되어있는지 확인
import numpy as np


In [ ]:
# 2차원
arr_2 = np.array

In [37]:
# 1로 3차원 만들기
print(np.ones((2,3,4), dtype= int))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [18]:
# 일정한 간격의 넘파이 배열 생성하기 
# n 만큼 차이나는 숫자 생성 
# linspace : N등분한 숫자 생성 
# 마지막꺼는 안나온다
print(np.arange(10, 30, 5))
print(np.arange(0,2,0.3))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
#N등분한 숫자
# 간격은 모르겠지만 무조건 5개가 나오게 해준다 (n,m,갯수)
# 간격이 중요하면 np.arange를 쓰고 갯수가 중요하면 np.linspace를 사용한다
print(np.linspace(start=1, stop=10, num=5, dtype=int))

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [ ]:
# np.arange의 마지막꺼는 안나온다
a = np.array([10,20,30,40])
b = np.arange((start=1,stop=5))
print(a)
print(b)

[10 20 30 40]
[1]


In [26]:
# 사칙연산이 가능한다
print(a + b)
print(a * b)
print(a / b)
print(a % b)

[11 22 33 44]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]


In [42]:
# 매트릭스 2차원 덧셈

A = np.array(
    [[1,1],
     [0,1]]
)

B = np.array(
    [[2,0],
     [3,4]]
)
# @는 2차원 연산할때 쓰는 기호
print(A@B)
# 2차원끼리도 넘파이는 * 가능하다
print(A*B)

[[5 4]
 [3 4]]
[[2 0]
 [0 4]]


In [ ]:
A = np.array([1,2,3,4])
B = np.array([1,1,3,3])

# 비교연산자 사용 가능 한데 사용하게 된다면 각각으로 표시되게 된다
print(A == B)
print(A > B)

[ True False  True False]


In [77]:
# 0~7까지 정수 값을 2행 4열로 만ㄹ기
arr1 = np.arange(0,8).reshape(2,4)
print(arr1)
# 모든요소의 총합을 구하고 싶을때
print(arr1.sum())
print(arr1.mean())
print(arr1.min())
print(arr1.max())
print(arr1.cumsum())
print(arr1.argmax())



[[0 1 2 3]
 [4 5 6 7]]
28
3.5
0
7
[ 0  1  3  6 10 15 21 28]
7


In [83]:
arr1 = np.arange(0,8).reshape(2,4)**2
print(arr1)
# 행이나 열로 복사를 하고 싶을때 
# 행이 1 이고 열이 0 
# 연산은 반대다...?
# axis = 0 은 열 기준으로 연산
print(arr1.mean(axis=0))

# axis = 1 은 행 기준으로 연산 
print(arr1.mean(axis=1))


[[ 0  1  4  9]
 [16 25 36 49]]
[ 8. 13. 20. 29.]
[ 3.5 31.5]


In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
# 논리연산을 하고 있다 - 논리형 인덱싱
b = a > 4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [90]:
# b를 인덱스로 넣으면 true만 출력하게 된다
# 원래 a 는 2차원 배열인데 슬라이싱을 하게 된다면
# b의 조건인 a>4 true는 나오고 false는 나오지 않는다
# 이걸 논리형 인덱싱이라고 한다
print(a[b])

[ 5  6  7  8  9 10 11]


In [94]:
# 정수형 인덱싱
a = np.array(['a','b','c','d','e','f','g','h'])
# b를 2번, d를 한번 e를 나오게끔 하는 코드
i = np.array([1, 1, 3, 4])

# 이를 출력하려면
print(a[i])
# 2차원 처럼 출력하려면
j = np.array([[3,4],[5,6]])
#d,e,f,g를 2차원의 형태로 출력하고 싶다
print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [111]:
# 퀴즈 예제 배열을 역순으로 출력하시오
b = np.array(['a', 'b', 'c', 'd'])

i = np.array([3,2,1,0])

print(b[i])

['d' 'c' 'b' 'a']


In [119]:
a = list(range(4))
b = a.reverse()
print(b)

None


In [121]:
a = np.arange(12).reshape(3,4)

print(a.shape)
print(a.ndim)
print(a)

(3, 4)
2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [122]:
b = a.reshape(2,6)
print(b)
print(b.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [124]:
# 행은 잘 모르겠고 열은 3개 였으면 좋겟으니까 행은 너가 계산해라 << -1

c = a.reshape(-1,3)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [125]:
# resize는 원본을 변경한다 << 잘 안씀

In [129]:
# 정말 많이 쓰는 1차원 배열로 변형하기 ravel() 함수와 reshape(-1)

a = np.arange(12).reshape(3,4)

# 평탄화 라고 합니다

print(a.ravel())
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [139]:
# 전치 연산(손바닥 뒤집기)
print(a.T)

b = a.T

print(b)

c = b.T

print(c)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([4,6,7,8]).reshape(2,2)

# 수직으로 붙일때 vstack vertical
print(np.vstack((a,b)))
# 수평을 붙일때 hstack horizontal
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [4 6]
 [7 8]]
[[1 2 4 6]
 [3 4 7 8]]


In [ ]:
# 분할해보겠습니다
a = np.arange(12).reshape(2,6)
print(a)

# 수직을 2개가 되도록 잘라보겟습니다
print(np.vsplit(a,2))
arr1 = np.vsplit(a,2)
type(arr1)
print(arr1)

# 수평을 2개가 되도록 잘라보겠습니다 
print(np.hsplit(a,3))
np.array(arr1)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


list