# Numpy 연습문제

In [204]:
import numpy as np

In [205]:
cus1 = np.array([150,25,0])
cus2 = np.array([200,30,0])
cus3 = np.array([50,10,1])
cus4 = np.array([300,45,0])
customer1 = np.vstack((cus1,cus2,cus3,cus4))
print(customer1)

[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]]


In [206]:
cus5 = np.array([120,20,0])
cus6 = np.array([180,35,1])
cus7 = np.array([75,5,0])
cus8 = np.array([160,25,0])
customer2 = np.vstack((cus5,cus6,cus7,cus8))

data_customer = np.vstack((customer1, customer2))
print(data_customer)


[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]
 [120  20   0]
 [180  35   1]
 [ 75   5   0]
 [160  25   0]]


In [228]:
customer_sum = data_customer.sum(0)
print(customer_sum)
average_sum = data_customer.mean(0)
print(average_sum)
combined_data = np.vstack((customer_sum,average_sum))

print(f'댓글 길이 총합 : {combined_data[0,0]}')
print(f'좋아요 수 총합 : {combined_data[0,1]}')
print(f'댓글 길이 평균 : {combined_data[1,0]}')
print(f'좋아요 수 평균 : {combined_data[1,1]}')




[1235  195    2]
[154.375  24.375   0.25 ]
댓글 길이 총합 : 1235.0
좋아요 수 총합 : 195.0
댓글 길이 평균 : 154.375
좋아요 수 평균 : 24.375


In [226]:
arr1 = np.vsplit(data_customer,4)
arr2 = np.vsplit(data_customer.reshape(8,3),4)
print(arr1)
print(arr2)





[array([[150,  25,   0],
       [200,  30,   0]]), array([[ 50,  10,   1],
       [300,  45,   0]]), array([[120,  20,   0],
       [180,  35,   1]]), array([[ 75,   5,   0],
       [160,  25,   0]])]
[array([[150,  25,   0],
       [200,  30,   0]]), array([[ 50,  10,   1],
       [300,  45,   0]]), array([[120,  20,   0],
       [180,  35,   1]]), array([[ 75,   5,   0],
       [160,  25,   0]])]


In [209]:
i = np.array([0,2,4])
print(data_customer[i])

[[150  25   0]
 [ 50  10   1]
 [120  20   0]]


In [210]:
data_customer.T

array([[150, 200,  50, 300, 120, 180,  75, 160],
       [ 25,  30,  10,  45,  20,  35,   5,  25],
       [  0,   0,   1,   0,   0,   1,   0,   0]])

In [234]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [255]:
i = np.array([0,10,0])

ii = np.vstack((i,i,i,i,i,i,i,i))
data_customer - ii
data_customer

ii

array([[ 0, 10,  0],
       [ 0, 10,  0],
       [ 0, 10,  0],
       [ 0, 10,  0],
       [ 0, 10,  0],
       [ 0, 10,  0],
       [ 0, 10,  0],
       [ 0, 10,  0]])

In [253]:
data_customer[:,1 ] = data_customer[:,1]-10
data_customer

array([[150,  35,   0],
       [200,  40,   0],
       [ 50,  20,   1],
       [300,  55,   0],
       [120,  30,   0],
       [180,  45,   1],
       [ 75,  15,   0],
       [160,  35,   0]])

In [238]:
print(data_customer)


[[150  45   0]
 [200  50   0]
 [ 50  30   1]
 [300  65   0]
 [120  40   0]
 [180  55   1]
 [ 75  25   0]
 [160  45   0]]


In [254]:
#문제 9
selected_customers = data_customer[(data_customer[:,0]>=100)&(data_customer[:,1]>=20)&(data_customer[:,2]==0)]
selected_customers

array([[150,  35,   0],
       [200,  40,   0],
       [300,  55,   0],
       [120,  30,   0],
       [160,  35,   0]])

In [256]:
print('I','T','O','L','D','U','B','I','T','C','H', sep=' ')

I T O L D U B I T C H


In [257]:
print('ㅋ'*14)

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ


In [ ]:
#넘파이는 수치적인 계산을 위해서 사용하는거다
#어레이를 생성하고 나서 
# dtype = 으로 타입 변경
# 데이터 값의 모양을 바꿀때 .reshape(y,x)
# a.shape, a.ndim a.dtype a.size
# linspace << 안의 갯수가 중요하다
# mask << 전체 데이터에서 : << 모든 2 << 3번째열 == 0 << 0인값만 찾자 combined[:,2] = arr1 = array([True, False ...]
# combined[arr1] = True 인 값만 출력이 됨
# argmax << 최댓값의 위치를 알고싶을때 
# j는 2차원 배열로 보여주는것 인덱싱도 해주는것도 있고 
# reshape(-1,3) << -1은 계산 안하고 3으로만 할테니 열은 너가 알아서 계산해라
# 
