# Numpy 소개

In [2]:
import numpy as np

# 브로드캐스팅 nd array 라고 아래 코드를 지칭한다
1 + np.array([1,2,3])

array([2, 3, 4])

In [3]:
# 기존 파이썬은 이걸 더하게 된다면 그냥 이어붙인다
[[2,3],[4,5]] + [[2,3],[4,5]]

[[2, 3], [4, 5], [2, 3], [4, 5]]

In [4]:
# np 라고 들여오는게 관습
import numpy as np

# nd array는 속끼리도 더한다
np.array([[2,3],[4,5]]) + np.array([[2,3],[4,5]])


array([[ 4,  6],
       [ 8, 10]])

# Numpy 배열 기초

In [5]:
#리스트가 아닌 Numpy 배열은 np.array() 함수를 통하여 생성할 수 있다

import numpy as np

# np.array 라는 객체 타입으로 생성이 되었다는걸 알 수 있다
arr = np.array([1,2,3])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

# 파이썬 기본 리스트에서 +를 사용하면 그냥 이어붙인다
list1 + list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
arr1 = np.array(list1)
arr2 = np.array(list2)
# 이걸 통해서 행열의 덧셈 혹은 곱셈을 할 수 있다
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [8]:
# 0차원 배열 - 스칼라
arr0d = np.array(1)
print("0차원 배열:", arr0d)

# 1차원 배열 - 백터
arr1d = np.array([1, 2, 3, 4, 5])
print("1차원 배열:", arr1d)

# 2차원 배열 - 메트릭스
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2차원 배열:", arr2d)

# 3차원 이상의 배열 - 텐서 << 인공지능은 결국 행열의 흐름이다
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3차원 배열:", arr3d)

0차원 배열: 1
1차원 배열: [1 2 3 4 5]
2차원 배열: [[1 2 3]
 [4 5 6]]
3차원 배열: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#0차원
a = np.array(1)
# 차원을 출력해주는 코드
a.ndim
#1 차원
# 결국 대괄호의 갯수 n이 n차원 인거다
a = np.array([1,2,3])
a.ndim
#2차원
a = np.array([[1,2,3],[4,5,6]])
a.ndim
#3차원
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a.ndim

3

In [10]:
#괄호 안에 괄호가 들어가주어야 한다
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# 첫번째 대괄호에서 3개가 생성이 되었고
# 두번째 대괄호에서 4개가 생성이 되었고
# 세번째 대괄호에서 2개가 생성이 되었다

np.zeros((3,4,2))


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
# 1로 이루어진 배열
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((2,3,4))
# 어떠한 형태로 만들어지는 3차원까지는 머릿속으로 그려져야 한다

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
# 저 배열을 특정 숫자로 채우고 싶을때
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [15]:
# 단위 행열은 행열의 곱셈을 했을때 자기자신이 나오도록 하는것
# 대각선이 1이고 나머지는 0인 행렬을 뜻한다
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# 범위배열 파이썬에서 range() 라는것을 했다
list(range(10))
# numpy는 선형대수, 소숫점으로 되어있는것도 많이 사용한다

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
# 0.5 씩 건너뛰게 해줄 수 있고, 2 씩 건너뛰게 해줄 수 있다 다 된다
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [18]:
# np.arange(시작,끝,간격) 
np.arange(0, 10, 2)
type(np.arange(0, 10, 0.5))


numpy.ndarray

In [19]:
#np.linspace() 는 시작점과 끝점 사이를 균등하게 나눈다
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
import random as rd

rd.randint(1,10)

4

In [21]:
# 랜덤도 np를 사용할 수 있다
np.random.randint(1,10,(2,3))

array([[9, 8, 9],
       [6, 8, 8]], dtype=int32)

In [22]:
# 랜덤에 랜덤도 가능함
np.random.random((2,3))

array([[0.43845822, 0.69228433, 0.30794684],
       [0.91365507, 0.6939429 , 0.05503637]])

In [23]:
np.random.seed(42)
np.random.randint(1,10,(2,3))


array([[7, 4, 8],
       [5, 7, 3]], dtype=int32)

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#이걸 통해 형태를 알 수 있다
arr.shape
#차원의 갯수
arr.ndim
#총 요소의 갯수
arr.size

6

In [25]:
np.arange(1, 7) #이것의 형태를 변화시켜주는 것이 .reshape() 이다

array([1, 2, 3, 4, 5, 6])

In [26]:
np.arange(1, 7).reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# 이미지도 행열이다 이미지에다 처리를 하고 싶으면 [0,0,0] 에다가 변경을 해주는 것이다

In [28]:
# 지정을 하지 않도 데이터타입이 들어간다
arr.dtype

dtype('int64')

In [29]:
np.array(([1,2,3]), dtype=np.float64)

array([1., 2., 3.])

# Numpy 연습문제 1

In [30]:
# 1. 1부터 10까지의 정수를 포함하는 1차은 NumPy 배열을 생성하세요.
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# 2. 2x3 형태의 2차원 배열을 생성하세요. 값은 [[1, 2, 3], [4, 5, 6]]으로 설정하세요.
np.arange(1,7).reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# 3. 3x3 크기의 0으로 채워진 배열을 생성하세요.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# 4. 2x2 크기의 1로 채워진 배열을 생성하세요.
arr1 = np.ones((2,2))
arr2 = np.full((2,2),1)
print(arr1)
print(arr2)

[[1. 1.]
 [1. 1.]]
[[1 1]
 [1 1]]


In [34]:
# 5. 배열의 차원(ndim)을 확인하는 코드를 작성하세요.
np.ndim([1,2,3])

1

In [35]:
# 1. 3x3 크기의 단위 행렬(identity matrix)을 생성하세요.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# 2. 2x4 크기의 배열을 생성하고 모든 값을 5로 채우세요.
np.full((2,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [37]:
# 3. 0부터 20까지 2 간격으로 숫자를 생성하는 arange 함수를 사용하세요.(20 포함)
np.arange(0,22,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [38]:
# 4. 0부터 1까지 균등하게 나눈 5개의 숫자를 linspace 함수로 생성하세요.
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
# 1. 시드 값을 42로 설정하세요.
import random as rd

rd.seed(42)

In [40]:
# 2. 2x3 크기의 0~1 사이 난수 배열을 생성하세요
arr1 = np.random.random((2,3))

In [41]:
# 3. 위에서 생성한 배열들의 형태(shape)와 크기(size)를 출력하세요.
arr1.size
arr2.shape

(2, 2)